#pragma once

#include "blackmagic/arg_count.h" // ARG_COUNT
#include "blackmagic/token.h"     // CONCAT

/**
 * @file
 * Generate code by calling a macro repeatedly
 */

/** To be used with @ref FOR */
#define EACH(...) ARG_COUNT(__VA_ARGS__) __VA_OPT__(,) __VA_ARGS__

/**
 * Call @p MACRO on each item of the @p LIST, forwarding extra arguments if any.
 *
 * __Example__
 * @code{.c}
 * FOR(EACH(A, B, C), F, X, Y)
 * @endcode
 * will expand to:
 * @code{.c}
 * F(X, Y, A)
 * F(X, Y, B)
 * F(X, Y, C)
 * @endcode
 * @param LIST shall be of the form `EACH(P0, P1, ..., Pn-1)`
 * @param MACRO shall be a function-like macro
 * @since 0.2
 */
#define FOR(LIST, MACRO, ...) FOR_(LIST, MACRO __VA_OPT__(,) __VA_ARGS__)

///@cond
#define FOR_(N, ...) CONCAT(FOR_, N)(__VA_ARGS__)
#define FOR_0(M)
#define FOR_1(A, M) \
	M(__VA_ARGS__ __VA_OPT__(,) A)
#define FOR_2(A, B, M) \
	M(__VA_ARGS__ __VA_OPT__(,) A) \
	M(__VA_ARGS__ __VA_OPT__(,) B)
#define FOR_3(A, B, C, M) \
	M(__VA_ARGS__ __VA_OPT__(,) A) \
	M(__VA_ARGS__ __VA_OPT__(,) B) \
	M(__VA_ARGS__ __VA_OPT__(,) C)
#define FOR_4(A, B, C, D, M) \
	M(__VA_ARGS__ __VA_OPT__(,) A) \
	M(__VA_ARGS__ __VA_OPT__(,) B) \
	M(__VA_ARGS__ __VA_OPT__(,) C) \
	M(__VA_ARGS__ __VA_OPT__(,) D)
#define FOR_5(AA,AB,AC,AD,AE, M, ...) \
	M(__VA_ARGS__ __VA_OPT__(,) AA) \
	FOR_4(AB,AC,AD,AE, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_6(AA,AB,AC,AD,AE,AF, M, ...) \
	FOR_2(AA,AB, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_2(AC,AD, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_2(AE,AF, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_7(AA,AB,AC,AD,AE,AF,AG, M, ...) \
	M(__VA_ARGS__ __VA_OPT__(,) AA) \
	FOR_6(AB,AC,AD,AE,AF,AG, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_8(AA,AB,AC,AD,AE,AF,AG,AH, M, ...) \
	FOR_4(AA,AB,AC,AD, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_4(AE,AF,AG,AH, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_9(AA,AB,AC,AD,AE,AF,AG,AH,AI, M, ...) \
	FOR_3(AA,AB,AC, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_3(AD,AE,AF, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_3(AG,AH,AI, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_10(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ, M, ...) \
	FOR_5(AA,AB,AC,AD,AE, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_5(AF,AG,AH,AI,AJ, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_11(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK, M, ...) \
	M(__VA_ARGS__ __VA_OPT__(,) AA) \
	FOR_10(AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_12(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL, M, ...) \
	FOR_4(AA,AB,AC,AD, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_4(AE,AF,AG,AH, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_4(AI,AJ,AK,AL, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_13(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM, M, ...) \
	M(__VA_ARGS__ __VA_OPT__(,) AA) \
	FOR_12(AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_14(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN, M, ...) \
	FOR_7(AA,AB,AC,AD,AE,AF,AG, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_7(AH,AI,AJ,AK,AL,AM,AN, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_15(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO, M, ...) \
	FOR_5(AA,AB,AC,AD,AE, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_5(AF,AG,AH,AI,AJ, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_5(AK,AL,AM,AN,AO, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_16(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP, M, ...) \
	FOR_8(AA,AB,AC,AD,AE,AF,AG,AH, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_8(AI,AJ,AK,AL,AM,AN,AO,AP, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_17(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ, M, ...) \
	M(__VA_ARGS__ __VA_OPT__(,) AA) \
	FOR_16(AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_18(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR, M, ...) \
	FOR_6(AA,AB,AC,AD,AE,AF, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_6(AG,AH,AI,AJ,AK,AL, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_6(AM,AN,AO,AP,AQ,AR, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_19(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS, M, ...) \
	M(__VA_ARGS__ __VA_OPT__(,) AA) \
	FOR_18(AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_20(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT, M, ...) \
	FOR_10(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_10(AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_21(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU, M, ...) \
	FOR_7(AA,AB,AC,AD,AE,AF,AG, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_7(AH,AI,AJ,AK,AL,AM,AN, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_7(AO,AP,AQ,AR,AS,AT,AU, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_22(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV, M, ...) \
	FOR_11(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_11(AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_23(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW, M, ...) \
	M(__VA_ARGS__ __VA_OPT__(,) AA) \
	FOR_22(AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_24(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX, M, ...) \
	FOR_8(AA,AB,AC,AD,AE,AF,AG,AH, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_8(AI,AJ,AK,AL,AM,AN,AO,AP, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_8(AQ,AR,AS,AT,AU,AV,AW,AX, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_25(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY, M, ...) \
	M(__VA_ARGS__ __VA_OPT__(,) AA) \
	FOR_24(AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_26(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ, M, ...) \
	FOR_13(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_13(AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_27(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA, M, ...) \
	FOR_9(AA,AB,AC,AD,AE,AF,AG,AH,AI, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_9(AJ,AK,AL,AM,AN,AO,AP,AQ,AR, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_9(AS,AT,AU,AV,AW,AX,AY,AZ,BA, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_28(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB, M, ...) \
	FOR_14(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_14(AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_29(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC, M, ...) \
	M(__VA_ARGS__ __VA_OPT__(,) AA) \
	FOR_28(AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_30(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD, M, ...) \
	FOR_10(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_10(AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_10(AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_31(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE, M, ...) \
	M(__VA_ARGS__ __VA_OPT__(,) AA) \
	FOR_30(AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_32(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF, M, ...) \
	FOR_16(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_16(AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_33(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG, M, ...) \
	FOR_11(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_11(AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_11(AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_34(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH, M, ...) \
	FOR_17(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_17(AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_35(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI, M, ...) \
	M(__VA_ARGS__ __VA_OPT__(,) AA) \
	FOR_34(AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_36(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ, M, ...) \
	FOR_12(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_12(AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_12(AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_37(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK, M, ...) \
	M(__VA_ARGS__ __VA_OPT__(,) AA) \
	FOR_36(AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_38(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL, M, ...) \
	FOR_19(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_19(AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_39(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM, M, ...) \
	FOR_13(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_13(AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_13(BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_40(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN, M, ...) \
	FOR_20(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_20(AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_41(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO, M, ...) \
	M(__VA_ARGS__ __VA_OPT__(,) AA) \
	FOR_40(AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_42(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP, M, ...) \
	FOR_14(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_14(AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_14(BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_43(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ, M, ...) \
	M(__VA_ARGS__ __VA_OPT__(,) AA) \
	FOR_42(AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_44(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR, M, ...) \
	FOR_22(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_22(AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_45(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS, M, ...) \
	FOR_15(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_15(AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_15(BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_46(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT, M, ...) \
	FOR_23(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_23(AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_47(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU, M, ...) \
	M(__VA_ARGS__ __VA_OPT__(,) AA) \
	FOR_46(AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_48(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV, M, ...) \
	FOR_16(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_16(AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_16(BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_49(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW, M, ...) \
	M(__VA_ARGS__ __VA_OPT__(,) AA) \
	FOR_48(AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_50(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX, M, ...) \
	FOR_25(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_25(AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_51(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY, M, ...) \
	FOR_17(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_17(AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_17(BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_52(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ, M, ...) \
	FOR_26(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_26(BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_53(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA, M, ...) \
	M(__VA_ARGS__ __VA_OPT__(,) AA) \
	FOR_52(AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_54(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB, M, ...) \
	FOR_18(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_18(AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_18(BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_55(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC, M, ...) \
	M(__VA_ARGS__ __VA_OPT__(,) AA) \
	FOR_54(AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_56(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD, M, ...) \
	FOR_28(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_28(BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_57(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE, M, ...) \
	FOR_19(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_19(AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_19(BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_58(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF, M, ...) \
	FOR_29(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_29(BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_59(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG, M, ...) \
	M(__VA_ARGS__ __VA_OPT__(,) AA) \
	FOR_58(AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_60(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH, M, ...) \
	FOR_20(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_20(AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_20(BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_61(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI, M, ...) \
	M(__VA_ARGS__ __VA_OPT__(,) AA) \
	FOR_60(AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_62(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ, M, ...) \
	FOR_31(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_31(BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_63(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK, M, ...) \
	FOR_21(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_21(AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_21(BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_64(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK,CL, M, ...) \
	FOR_32(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_32(BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK,CL, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_65(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK,CL,CM, M, ...) \
	M(__VA_ARGS__ __VA_OPT__(,) AA) \
	FOR_64(AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK,CL,CM, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_66(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK,CL,CM,CN, M, ...) \
	FOR_22(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_22(AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_22(BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK,CL,CM,CN, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_67(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK,CL,CM,CN,CO, M, ...) \
	M(__VA_ARGS__ __VA_OPT__(,) AA) \
	FOR_66(AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK,CL,CM,CN,CO, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_68(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK,CL,CM,CN,CO,CP, M, ...) \
	FOR_34(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_34(BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK,CL,CM,CN,CO,CP, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_69(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK,CL,CM,CN,CO,CP,CQ, M, ...) \
	FOR_23(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_23(AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_23(BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK,CL,CM,CN,CO,CP,CQ, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_70(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK,CL,CM,CN,CO,CP,CQ,CR, M, ...) \
	FOR_35(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_35(BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK,CL,CM,CN,CO,CP,CQ,CR, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_71(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK,CL,CM,CN,CO,CP,CQ,CR,CS, M, ...) \
	M(__VA_ARGS__ __VA_OPT__(,) AA) \
	FOR_70(AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK,CL,CM,CN,CO,CP,CQ,CR,CS, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_72(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK,CL,CM,CN,CO,CP,CQ,CR,CS,CT, M, ...) \
	FOR_24(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_24(AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_24(BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK,CL,CM,CN,CO,CP,CQ,CR,CS,CT, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_73(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK,CL,CM,CN,CO,CP,CQ,CR,CS,CT,CU, M, ...) \
	M(__VA_ARGS__ __VA_OPT__(,) AA) \
	FOR_72(AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK,CL,CM,CN,CO,CP,CQ,CR,CS,CT,CU, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_74(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK,CL,CM,CN,CO,CP,CQ,CR,CS,CT,CU,CV, M, ...) \
	FOR_37(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_37(BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK,CL,CM,CN,CO,CP,CQ,CR,CS,CT,CU,CV, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_75(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK,CL,CM,CN,CO,CP,CQ,CR,CS,CT,CU,CV,CW, M, ...) \
	FOR_25(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_25(AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_25(BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK,CL,CM,CN,CO,CP,CQ,CR,CS,CT,CU,CV,CW, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_76(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK,CL,CM,CN,CO,CP,CQ,CR,CS,CT,CU,CV,CW,CX, M, ...) \
	FOR_38(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_38(BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK,CL,CM,CN,CO,CP,CQ,CR,CS,CT,CU,CV,CW,CX, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_77(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK,CL,CM,CN,CO,CP,CQ,CR,CS,CT,CU,CV,CW,CX,CY, M, ...) \
	M(__VA_ARGS__ __VA_OPT__(,) AA) \
	FOR_76(AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK,CL,CM,CN,CO,CP,CQ,CR,CS,CT,CU,CV,CW,CX,CY, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_78(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK,CL,CM,CN,CO,CP,CQ,CR,CS,CT,CU,CV,CW,CX,CY,CZ, M, ...) \
	FOR_26(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_26(BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_26(CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK,CL,CM,CN,CO,CP,CQ,CR,CS,CT,CU,CV,CW,CX,CY,CZ, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_79(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK,CL,CM,CN,CO,CP,CQ,CR,CS,CT,CU,CV,CW,CX,CY,CZ,DA, M, ...) \
	M(__VA_ARGS__ __VA_OPT__(,) AA) \
	FOR_78(AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK,CL,CM,CN,CO,CP,CQ,CR,CS,CT,CU,CV,CW,CX,CY,CZ,DA, M __VA_OPT__(,) __VA_ARGS__)
#define FOR_80(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK,CL,CM,CN,CO,CP,CQ,CR,CS,CT,CU,CV,CW,CX,CY,CZ,DA,DB, M, ...) \
	FOR_40(AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN, M __VA_OPT__(,) __VA_ARGS__) \
	FOR_40(BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK,CL,CM,CN,CO,CP,CQ,CR,CS,CT,CU,CV,CW,CX,CY,CZ,DA,DB, M __VA_OPT__(,) __VA_ARGS__)
///@endcond
